name: Docker CD Pipeline

on:
  workflow_run:
    workflows: ["Python CI + Security Scan"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/exo-j:${{ github.sha }} .
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/exo-j:${{ github.sha }}
