name: Docker CD Pipeline

on:
  workflow_run:
    workflows: ["Python CI + Security Scan"]
    types:
      - completed
  workflow_dispatch:  # Permet de lancer le CD manuellement

permissions:
  contents: read
  security-events: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Condition : exécute si CI a réussi OU si lancement manuel
    if: |
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || 
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/exo-j:${{ github.sha }}" .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/exo-j:${{ github.sha }}
